<?php

declare(strict_types=1);
require __DIR__.'/../config/bootstrap.php';
/** @var PDO $pdo */
use App\Security\Auth;

$auth = new Auth($pdo);
$rooms = $pdo->query('SELECT rt.*,c.name category_name,(SELECT COUNT(*) FROM rooms r WHERE r.room_type_id=rt.id AND r.active=1) inventory FROM room_types rt INNER JOIN categories c ON c.id=rt.category_id WHERE rt.active=1 ORDER BY rt.featured DESC,rt.base_price LIMIT 3')->fetchAll();
$services = $pdo->query('SELECT * FROM services WHERE active=1 ORDER BY id LIMIT 4')->fetchAll();
$review = $pdo->query("SELECT reviews.rating,reviews.comment,CONCAT(clients.first_name,' ',LEFT(clients.last_name,1),'.') client_name FROM reviews INNER JOIN clients ON clients.id=reviews.client_id WHERE reviews.status='published' ORDER BY reviews.created_at DESC LIMIT 1")->fetch();
$stats = ['rooms' => (int)$pdo->query('SELECT COUNT(*) FROM rooms WHERE active=1')->fetchColumn(),'guests' => (int)$pdo->query('SELECT COUNT(*) FROM clients')->fetchColumn(),'services' => (int)$pdo->query('SELECT COUNT(*) FROM services WHERE active=1')->fetchColumn()];
$dateIn = (new DateTimeImmutable('tomorrow'))->format('Y-m-d');
$dateOut = (new DateTimeImmutable('+3 days'))->format('Y-m-d');
$title = 'Отель';
$active = 'home';
require __DIR__.'/../templates/site/header.php';
?>
<main class="product-page home-page"><section class="home-hero"><div class="product-container home-hero-content"><span class="eyebrow light">Советский · с 2010 года</span><h1>Ваше тихое место<br>на севере</h1><p>Комфортный городской отель с прямым бронированием, заботой 24/7 и услугами, которые можно заказать онлайн.</p><a class="product-button" href="#booking">Найти номер</a></div></section>
<section id="booking" class="product-container search-overlap"><form class="search-card home-search" action="/rooms.php"><label><span>Заезд</span><input type="date" name="date_in" value="<?=e($dateIn)?>" min="<?=e(date('Y-m-d'))?>" required></label><label><span>Выезд</span><input type="date" name="date_out" value="<?=e($dateOut)?>" min="<?=e(date('Y-m-d', strtotime('+1 day')))?>" required></label><label><span>Взрослые</span><select name="adults"><?php for ($i = 1;$i <= 6;++$i):?><option value="<?=$i?>" <?=$i === 2 ? 'selected' : ''?>><?=$i?></option><?php endfor;?></select></label><label><span>Дети</span><select name="children"><?php for ($i = 0;$i <= 4;++$i):?><option value="<?=$i?>"><?=$i?></option><?php endfor;?></select></label><button class="product-button">Проверить даты</button></form></section>
<section class="product-container home-intro"><div><span class="eyebrow">Отель в Советском</span><h2>Приезжайте отдыхать,<br>остальное — на нас</h2></div><div><p>Мы рядом с вокзалом, дорогой на Югорск и аэропортом. Здесь одинаково удобно остановиться в командировке, путешествии или на длинные выходные.</p><div class="home-facts"><span><strong><?=$stats['rooms']?></strong>номеров</span><span><strong>24/7</strong>ресепшен</span><span><strong><?=$stats['services']?></strong>услуг онлайн</span></div></div></section>
<section class="product-container home-section"><div class="section-heading row-heading"><div><span class="eyebrow">Номерной фонд</span><h2>Выберите свой ритм</h2></div><a class="back-link" href="/rooms.php">Все номера →</a></div><div class="room-grid product-room-grid"><?php foreach ($rooms as $room):?><article class="product-room-card"><a class="room-photo" href="/rooms-single.php?id=<?=e((string)$room['id'])?>" style="background-image:url('/images/<?=e((string)$room['photo'])?>')"><?php if ((int)$room['featured'] === 1):?><span class="featured-chip">Рекомендуем</span><?php endif;?></a><div class="room-card-body"><span class="eyebrow"><?=e((string)$room['category_name'])?> · <?=e((string)$room['size_sqm'])?> м²</span><h3><a href="/rooms-single.php?id=<?=e((string)$room['id'])?>"><?=e((string)$room['name'])?></a></h3><p><?=e((string)$room['short_description'])?></p><div class="room-price-row"><div><small>от</small><strong><?=e(money($room['base_price']))?></strong><span>за ночь</span></div><a class="product-button small" href="/rooms-single.php?id=<?=e((string)$room['id'])?>">Подробнее</a></div></div></article><?php endforeach;?></div></section>
<section class="home-services"><div class="product-container"><div class="section-heading"><span class="eyebrow light">Не только проживание</span><h2>Сервис в один клик</h2></div><div class="home-service-grid"><?php foreach ($services as $service):?><a href="/services.php"><span><?=e((string)($service['icon'] ?: '✦'))?></span><strong><?=e((string)$service['name'])?></strong><small>от <?=e(money($service['price']))?></small></a><?php endforeach;?></div></div></section>
<section class="product-container home-trust"><div><span class="eyebrow">Полный цифровой путь</span><h2>Бронируйте без звонка</h2><p>Личный кабинет хранит поездки, счета и услуги. Тестовая оплата показывает весь сценарий продукта без списания денег.</p><div class="button-group"><a class="product-button" href="/rooms.php">Выбрать номер</a><a class="product-button secondary" href="/services.php">Посмотреть услуги</a></div></div><?php if ($review):?><blockquote><span><?=str_repeat('★', (int)$review['rating'])?></span><p>«<?=e((string)$review['comment'])?>»</p><footer><?=e((string)$review['client_name'])?></footer></blockquote><?php endif;?></section></main>
<?php require __DIR__.'/../templates/site/footer.php';?>
